all:
  hosts:
    inetRouter: 
      ansible_host: 127.0.0.1
      ansible_port: 22220
    centralRouter:
      ansible_host: 127.0.0.1
      ansible_port: 22221
    office1Router:
      ansible_host: 127.0.0.1
      ansible_port: 22222
    testServer1:
      ansible_host: 127.0.0.1
      ansible_port: 22223
    testClient1:
      ansible_host: 127.0.0.1
      ansible_port: 22224
    testServer2:
      ansible_host: 127.0.0.1
      ansible_port: 22225
    testClient2:
      ansible_host: 127.0.0.1
      ansible_port: 22226