---
all:
  hosts:
    ns01:
      ansible_host: 127.0.0.1
      ansible_port: 22220
    ns02:
      ansible_host: 127.0.0.1
      ansible_port: 22221
    client1:
      ansible_host: 127.0.0.1
      ansible_port: 22222
    client2:
      ansible_host: 127.0.0.1
      ansible_port: 22223