forwarding: true

ipv4:
  dhcp:
    - if: eth0
  static:
    - if: eth1
      addr: 192.168.255.2
      subnet: 30
    - if: eth2
      addr: 192.168.0.1
      subnet: 28
    - if: eth3
      addr: 192.168.0.33
      subnet: 28
    - if: eth4
      addr: 192.168.0.65
      subnet: 26
    - if: eth5
      addr: 192.168.255.5
      subnet: 30
    - if: eth6
      addr: 192.168.255.9
      subnet: 30

gateways:
  - if: eth1
    gateway: 192.168.255.1